### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [wanchichang/git-practice#1]
在介紹每個物件時，有搭配實驗去驗證與說明，這是很棒的做法，也都有附上參考資料，做得很好。

不過，commit message style 這題似乎沒有寫到？

**Comment by azole** [comment]
<img width="152" alt="image" src="https://github.com/user-attachments/assets/172fa71e-38fc-4d2f-9f1e-525d6e05b23a">

.DS_Store 這個檔案是應該要被推上 github repo 的嗎？

**Comment by wanchichang** [comment]
> 在介紹每個物件時，有搭配實驗去驗證與說明，這是很棒的做法，也都有附上參考資料，做得很好。
> 
> 不過，commit message style 這題似乎沒有寫到？

commit message style 的部分我是一併寫在commit的介紹裡 [commit 介紹連結](https://github.com/wanchichang/git-practice/blob/main/git.md#commit)
如圖：
<img width="289" alt="截圖 2024-09-19 下午4 50 07" src="https://github.com/user-attachments/assets/fdb422e1-d919-426e-9ce6-b6c7c235d07f">

謝謝老師的回饋！我以後寫文件時會再留意每個項目的編排，盡量讓閱讀的人能一目瞭然

**Comment by wanchichang** [comment]
> <img alt="image" width="152" src="https://private-user-images.githubusercontent.com/2560515/368723474-172fa71e-38fc-4d2f-9f1e-525d6e05b23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzYxMTQsIm5iZiI6MTcyNjczNTgxNCwicGF0aCI6Ii8yNTYwNTE1LzM2ODcyMzQ3NC0xNzJmYTcxZS0zOGZjLTRkMmYtOWYxZS01MjVkNmUwNWIyM2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMDg1MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGJmODhkZTY2Y2RiNmE1MGVhZTJlODk1MjQzMTc5MmQ4MjUwNzZhODVjNjk0YjA3OTU2NTRkNGEwNDAwMjMxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wQUcsmgWH1IsO04qXzxbT_JXvHaGJk6V7NHLyyz12uU">
> .DS_Store 這個檔案是應該要被推上 github repo 的嗎？

.DS_Store 這個檔案的確不該被推上github，我當時沒注意到，感謝老師提醒，已加上`.gitignore`並將不該被推上來的檔案移除了

**Comment by azole** [comment]
很好喔，立刻善用 .gitignore 讚讚
